[package]
name = "project_runtime_sdk"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
project_runtime_abi = { path = "../project_runtime_abi" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
